main: org.fortyoteam.darsasystem.Main
name: DarsaSystem
description: Darsa Build Battle System
version: 1.19
api-version: 1.19

commands:
  buff:
    description: Give players buff
    usage: /buff [name]
  shop:
    description: Open Shop GUI
    usage: /shop
  blacksmith:
    description: Open Blacksmith
    aliases:
      - bls
    usage: /blacksmith
  dsr:
    description: Reload Config
    usage: /dsr
  darsaitem:
    description: Give player Custom Darsa Item
    aliases:
      - dsi
    usage: /darsaitem [itemname]
  darsahelp:
    description: Show list of all commands
    usage: /darsahelp
    aliases:
      - dsh